spring:
  application:
    name: agenda-api
  datasource:
    url: jdbc:postgresql://localhost:5436/diary
    username: admin
    password: agenda
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: chave-super-secreta
  expiration: 86400000
