spring:
  application:
    name: ${APP_NAME:agenda-api}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/diary}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:agenda}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:uma-chave-bem-grande-com-mais-de-32-chars-123456}
  expiration: ${JWT_EXPIRATION:86400000}
